#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinansalTablolarAnalizi.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Finans")]
	public partial class DataBase1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUVYK(UVYK instance);
    partial void UpdateUVYK(UVYK instance);
    partial void DeleteUVYK(UVYK instance);
    partial void InsertDuranVarlik(DuranVarlik instance);
    partial void UpdateDuranVarlik(DuranVarlik instance);
    partial void DeleteDuranVarlik(DuranVarlik instance);
    partial void InsertDonenVarlik(DonenVarlik instance);
    partial void UpdateDonenVarlik(DonenVarlik instance);
    partial void DeleteDonenVarlik(DonenVarlik instance);
    partial void InsertAktifPasif(AktifPasif instance);
    partial void UpdateAktifPasif(AktifPasif instance);
    partial void DeleteAktifPasif(AktifPasif instance);
    partial void InsertKullanici(Kullanici instance);
    partial void UpdateKullanici(Kullanici instance);
    partial void DeleteKullanici(Kullanici instance);
    partial void InsertOzkaynak(Ozkaynak instance);
    partial void UpdateOzkaynak(Ozkaynak instance);
    partial void DeleteOzkaynak(Ozkaynak instance);
    partial void InsertKVYK(KVYK instance);
    partial void UpdateKVYK(KVYK instance);
    partial void DeleteKVYK(KVYK instance);
    #endregion
		
		public DataBase1DataContext() : 
				base(global::FinansalTablolarAnalizi.Properties.Settings.Default.FinansConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataBase1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBase1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBase1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBase1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UVYK> UVYKs
		{
			get
			{
				return this.GetTable<UVYK>();
			}
		}
		
		public System.Data.Linq.Table<DuranVarlik> DuranVarliks
		{
			get
			{
				return this.GetTable<DuranVarlik>();
			}
		}
		
		public System.Data.Linq.Table<DonenVarlik> DonenVarliks
		{
			get
			{
				return this.GetTable<DonenVarlik>();
			}
		}
		
		public System.Data.Linq.Table<AktifPasif> AktifPasifs
		{
			get
			{
				return this.GetTable<AktifPasif>();
			}
		}
		
		public System.Data.Linq.Table<Kullanici> Kullanicis
		{
			get
			{
				return this.GetTable<Kullanici>();
			}
		}
		
		public System.Data.Linq.Table<Ozkaynak> Ozkaynaks
		{
			get
			{
				return this.GetTable<Ozkaynak>();
			}
		}
		
		public System.Data.Linq.Table<KVYK> KVYKs
		{
			get
			{
				return this.GetTable<KVYK>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UVYK")]
	public partial class UVYK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uvyk_id;
		
		private System.Nullable<decimal> _mevduatlar;
		
		private System.Nullable<decimal> _finansal_borclar;
		
		private System.Nullable<decimal> _factoring_borclar;
		
		private System.Nullable<decimal> _sigorta_karsiligi;
		
		private System.Nullable<decimal> _dfinansal_yukumluluk;
		
		private System.Nullable<decimal> _ticari_borclar;
		
		private System.Nullable<decimal> _alinan_avanslar;
		
		private System.Nullable<decimal> _bloke_hesaplar;
		
		private System.Nullable<decimal> _iliskili_borclar;
		
		private System.Nullable<decimal> _alinan_krediler;
		
		private System.Nullable<decimal> _borcgider_karsiligi;
		
		private System.Nullable<decimal> _ertelenmis_gelirler;
		
		private System.Nullable<decimal> _pozitif_negatif;
		
		private System.Nullable<decimal> _duzun_borclar;
		
		private string _sirket_adi;
		
		private System.Nullable<decimal> _uvyk_toplami;
		
		private string _kayit_adi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuvyk_idChanging(int value);
    partial void Onuvyk_idChanged();
    partial void OnmevduatlarChanging(System.Nullable<decimal> value);
    partial void OnmevduatlarChanged();
    partial void Onfinansal_borclarChanging(System.Nullable<decimal> value);
    partial void Onfinansal_borclarChanged();
    partial void Onfactoring_borclarChanging(System.Nullable<decimal> value);
    partial void Onfactoring_borclarChanged();
    partial void Onsigorta_karsiligiChanging(System.Nullable<decimal> value);
    partial void Onsigorta_karsiligiChanged();
    partial void Ondfinansal_yukumlulukChanging(System.Nullable<decimal> value);
    partial void Ondfinansal_yukumlulukChanged();
    partial void Onticari_borclarChanging(System.Nullable<decimal> value);
    partial void Onticari_borclarChanged();
    partial void Onalinan_avanslarChanging(System.Nullable<decimal> value);
    partial void Onalinan_avanslarChanged();
    partial void Onbloke_hesaplarChanging(System.Nullable<decimal> value);
    partial void Onbloke_hesaplarChanged();
    partial void Oniliskili_borclarChanging(System.Nullable<decimal> value);
    partial void Oniliskili_borclarChanged();
    partial void Onalinan_kredilerChanging(System.Nullable<decimal> value);
    partial void Onalinan_kredilerChanged();
    partial void Onborcgider_karsiligiChanging(System.Nullable<decimal> value);
    partial void Onborcgider_karsiligiChanged();
    partial void Onertelenmis_gelirlerChanging(System.Nullable<decimal> value);
    partial void Onertelenmis_gelirlerChanged();
    partial void Onpozitif_negatifChanging(System.Nullable<decimal> value);
    partial void Onpozitif_negatifChanged();
    partial void Onduzun_borclarChanging(System.Nullable<decimal> value);
    partial void Onduzun_borclarChanged();
    partial void Onsirket_adiChanging(string value);
    partial void Onsirket_adiChanged();
    partial void Onuvyk_toplamiChanging(System.Nullable<decimal> value);
    partial void Onuvyk_toplamiChanged();
    partial void Onkayit_adiChanging(string value);
    partial void Onkayit_adiChanged();
    #endregion
		
		public UVYK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uvyk_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uvyk_id
		{
			get
			{
				return this._uvyk_id;
			}
			set
			{
				if ((this._uvyk_id != value))
				{
					this.Onuvyk_idChanging(value);
					this.SendPropertyChanging();
					this._uvyk_id = value;
					this.SendPropertyChanged("uvyk_id");
					this.Onuvyk_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mevduatlar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> mevduatlar
		{
			get
			{
				return this._mevduatlar;
			}
			set
			{
				if ((this._mevduatlar != value))
				{
					this.OnmevduatlarChanging(value);
					this.SendPropertyChanging();
					this._mevduatlar = value;
					this.SendPropertyChanged("mevduatlar");
					this.OnmevduatlarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finansal_borclar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> finansal_borclar
		{
			get
			{
				return this._finansal_borclar;
			}
			set
			{
				if ((this._finansal_borclar != value))
				{
					this.Onfinansal_borclarChanging(value);
					this.SendPropertyChanging();
					this._finansal_borclar = value;
					this.SendPropertyChanged("finansal_borclar");
					this.Onfinansal_borclarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factoring_borclar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> factoring_borclar
		{
			get
			{
				return this._factoring_borclar;
			}
			set
			{
				if ((this._factoring_borclar != value))
				{
					this.Onfactoring_borclarChanging(value);
					this.SendPropertyChanging();
					this._factoring_borclar = value;
					this.SendPropertyChanged("factoring_borclar");
					this.Onfactoring_borclarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sigorta_karsiligi", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> sigorta_karsiligi
		{
			get
			{
				return this._sigorta_karsiligi;
			}
			set
			{
				if ((this._sigorta_karsiligi != value))
				{
					this.Onsigorta_karsiligiChanging(value);
					this.SendPropertyChanging();
					this._sigorta_karsiligi = value;
					this.SendPropertyChanged("sigorta_karsiligi");
					this.Onsigorta_karsiligiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dfinansal_yukumluluk", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> dfinansal_yukumluluk
		{
			get
			{
				return this._dfinansal_yukumluluk;
			}
			set
			{
				if ((this._dfinansal_yukumluluk != value))
				{
					this.Ondfinansal_yukumlulukChanging(value);
					this.SendPropertyChanging();
					this._dfinansal_yukumluluk = value;
					this.SendPropertyChanged("dfinansal_yukumluluk");
					this.Ondfinansal_yukumlulukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ticari_borclar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> ticari_borclar
		{
			get
			{
				return this._ticari_borclar;
			}
			set
			{
				if ((this._ticari_borclar != value))
				{
					this.Onticari_borclarChanging(value);
					this.SendPropertyChanging();
					this._ticari_borclar = value;
					this.SendPropertyChanged("ticari_borclar");
					this.Onticari_borclarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alinan_avanslar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> alinan_avanslar
		{
			get
			{
				return this._alinan_avanslar;
			}
			set
			{
				if ((this._alinan_avanslar != value))
				{
					this.Onalinan_avanslarChanging(value);
					this.SendPropertyChanging();
					this._alinan_avanslar = value;
					this.SendPropertyChanged("alinan_avanslar");
					this.Onalinan_avanslarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bloke_hesaplar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> bloke_hesaplar
		{
			get
			{
				return this._bloke_hesaplar;
			}
			set
			{
				if ((this._bloke_hesaplar != value))
				{
					this.Onbloke_hesaplarChanging(value);
					this.SendPropertyChanging();
					this._bloke_hesaplar = value;
					this.SendPropertyChanged("bloke_hesaplar");
					this.Onbloke_hesaplarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iliskili_borclar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> iliskili_borclar
		{
			get
			{
				return this._iliskili_borclar;
			}
			set
			{
				if ((this._iliskili_borclar != value))
				{
					this.Oniliskili_borclarChanging(value);
					this.SendPropertyChanging();
					this._iliskili_borclar = value;
					this.SendPropertyChanged("iliskili_borclar");
					this.Oniliskili_borclarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alinan_krediler", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> alinan_krediler
		{
			get
			{
				return this._alinan_krediler;
			}
			set
			{
				if ((this._alinan_krediler != value))
				{
					this.Onalinan_kredilerChanging(value);
					this.SendPropertyChanging();
					this._alinan_krediler = value;
					this.SendPropertyChanged("alinan_krediler");
					this.Onalinan_kredilerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_borcgider_karsiligi", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> borcgider_karsiligi
		{
			get
			{
				return this._borcgider_karsiligi;
			}
			set
			{
				if ((this._borcgider_karsiligi != value))
				{
					this.Onborcgider_karsiligiChanging(value);
					this.SendPropertyChanging();
					this._borcgider_karsiligi = value;
					this.SendPropertyChanged("borcgider_karsiligi");
					this.Onborcgider_karsiligiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ertelenmis_gelirler", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> ertelenmis_gelirler
		{
			get
			{
				return this._ertelenmis_gelirler;
			}
			set
			{
				if ((this._ertelenmis_gelirler != value))
				{
					this.Onertelenmis_gelirlerChanging(value);
					this.SendPropertyChanging();
					this._ertelenmis_gelirler = value;
					this.SendPropertyChanged("ertelenmis_gelirler");
					this.Onertelenmis_gelirlerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pozitif_negatif", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> pozitif_negatif
		{
			get
			{
				return this._pozitif_negatif;
			}
			set
			{
				if ((this._pozitif_negatif != value))
				{
					this.Onpozitif_negatifChanging(value);
					this.SendPropertyChanging();
					this._pozitif_negatif = value;
					this.SendPropertyChanged("pozitif_negatif");
					this.Onpozitif_negatifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duzun_borclar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> duzun_borclar
		{
			get
			{
				return this._duzun_borclar;
			}
			set
			{
				if ((this._duzun_borclar != value))
				{
					this.Onduzun_borclarChanging(value);
					this.SendPropertyChanging();
					this._duzun_borclar = value;
					this.SendPropertyChanged("duzun_borclar");
					this.Onduzun_borclarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sirket_adi", DbType="NVarChar(500)")]
		public string sirket_adi
		{
			get
			{
				return this._sirket_adi;
			}
			set
			{
				if ((this._sirket_adi != value))
				{
					this.Onsirket_adiChanging(value);
					this.SendPropertyChanging();
					this._sirket_adi = value;
					this.SendPropertyChanged("sirket_adi");
					this.Onsirket_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uvyk_toplami", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> uvyk_toplami
		{
			get
			{
				return this._uvyk_toplami;
			}
			set
			{
				if ((this._uvyk_toplami != value))
				{
					this.Onuvyk_toplamiChanging(value);
					this.SendPropertyChanging();
					this._uvyk_toplami = value;
					this.SendPropertyChanged("uvyk_toplami");
					this.Onuvyk_toplamiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kayit_adi", DbType="NVarChar(500)")]
		public string kayit_adi
		{
			get
			{
				return this._kayit_adi;
			}
			set
			{
				if ((this._kayit_adi != value))
				{
					this.Onkayit_adiChanging(value);
					this.SendPropertyChanging();
					this._kayit_adi = value;
					this.SendPropertyChanged("kayit_adi");
					this.Onkayit_adiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DuranVarlik")]
	public partial class DuranVarlik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _duran_id;
		
		private System.Nullable<decimal> _menkul_kiymetler;
		
		private System.Nullable<decimal> _krediler_avanslar;
		
		private System.Nullable<decimal> _factoring_alacaklar;
		
		private System.Nullable<decimal> _uvadeli_ticarialacak;
		
		private System.Nullable<decimal> _fkiralama_alacak;
		
		private System.Nullable<decimal> _türev_enstrümanlar;
		
		private System.Nullable<decimal> _finansal_yatirim;
		
		private System.Nullable<decimal> _canli_varliklar;
		
		private System.Nullable<decimal> _stoklar;
		
		private System.Nullable<decimal> _mduran_varliklar;
		
		private System.Nullable<decimal> _molmayan_duranvarlik;
		
		private System.Nullable<decimal> _finansal_duranvarlik;
		
		private System.Nullable<decimal> _pesinodenmis_giderler;
		
		private System.Nullable<decimal> _pozitif_negatif;
		
		private string _sirket_adi;
		
		private System.Nullable<decimal> _duranvarlik_toplami;
		
		private string _kayit_adi;
		
		private System.Nullable<decimal> _dduran_varliklar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onduran_idChanging(int value);
    partial void Onduran_idChanged();
    partial void Onmenkul_kiymetlerChanging(System.Nullable<decimal> value);
    partial void Onmenkul_kiymetlerChanged();
    partial void Onkrediler_avanslarChanging(System.Nullable<decimal> value);
    partial void Onkrediler_avanslarChanged();
    partial void Onfactoring_alacaklarChanging(System.Nullable<decimal> value);
    partial void Onfactoring_alacaklarChanged();
    partial void Onuvadeli_ticarialacakChanging(System.Nullable<decimal> value);
    partial void Onuvadeli_ticarialacakChanged();
    partial void Onfkiralama_alacakChanging(System.Nullable<decimal> value);
    partial void Onfkiralama_alacakChanged();
    partial void Ontürev_enstrümanlarChanging(System.Nullable<decimal> value);
    partial void Ontürev_enstrümanlarChanged();
    partial void Onfinansal_yatirimChanging(System.Nullable<decimal> value);
    partial void Onfinansal_yatirimChanged();
    partial void Oncanli_varliklarChanging(System.Nullable<decimal> value);
    partial void Oncanli_varliklarChanged();
    partial void OnstoklarChanging(System.Nullable<decimal> value);
    partial void OnstoklarChanged();
    partial void Onmduran_varliklarChanging(System.Nullable<decimal> value);
    partial void Onmduran_varliklarChanged();
    partial void Onmolmayan_duranvarlikChanging(System.Nullable<decimal> value);
    partial void Onmolmayan_duranvarlikChanged();
    partial void Onfinansal_duranvarlikChanging(System.Nullable<decimal> value);
    partial void Onfinansal_duranvarlikChanged();
    partial void Onpesinodenmis_giderlerChanging(System.Nullable<decimal> value);
    partial void Onpesinodenmis_giderlerChanged();
    partial void Onpozitif_negatifChanging(System.Nullable<decimal> value);
    partial void Onpozitif_negatifChanged();
    partial void Onsirket_adiChanging(string value);
    partial void Onsirket_adiChanged();
    partial void Onduranvarlik_toplamiChanging(System.Nullable<decimal> value);
    partial void Onduranvarlik_toplamiChanged();
    partial void Onkayit_adiChanging(string value);
    partial void Onkayit_adiChanged();
    partial void Ondduran_varliklarChanging(System.Nullable<decimal> value);
    partial void Ondduran_varliklarChanged();
    #endregion
		
		public DuranVarlik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duran_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int duran_id
		{
			get
			{
				return this._duran_id;
			}
			set
			{
				if ((this._duran_id != value))
				{
					this.Onduran_idChanging(value);
					this.SendPropertyChanging();
					this._duran_id = value;
					this.SendPropertyChanged("duran_id");
					this.Onduran_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menkul_kiymetler", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> menkul_kiymetler
		{
			get
			{
				return this._menkul_kiymetler;
			}
			set
			{
				if ((this._menkul_kiymetler != value))
				{
					this.Onmenkul_kiymetlerChanging(value);
					this.SendPropertyChanging();
					this._menkul_kiymetler = value;
					this.SendPropertyChanged("menkul_kiymetler");
					this.Onmenkul_kiymetlerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_krediler_avanslar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> krediler_avanslar
		{
			get
			{
				return this._krediler_avanslar;
			}
			set
			{
				if ((this._krediler_avanslar != value))
				{
					this.Onkrediler_avanslarChanging(value);
					this.SendPropertyChanging();
					this._krediler_avanslar = value;
					this.SendPropertyChanged("krediler_avanslar");
					this.Onkrediler_avanslarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factoring_alacaklar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> factoring_alacaklar
		{
			get
			{
				return this._factoring_alacaklar;
			}
			set
			{
				if ((this._factoring_alacaklar != value))
				{
					this.Onfactoring_alacaklarChanging(value);
					this.SendPropertyChanging();
					this._factoring_alacaklar = value;
					this.SendPropertyChanged("factoring_alacaklar");
					this.Onfactoring_alacaklarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uvadeli_ticarialacak", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> uvadeli_ticarialacak
		{
			get
			{
				return this._uvadeli_ticarialacak;
			}
			set
			{
				if ((this._uvadeli_ticarialacak != value))
				{
					this.Onuvadeli_ticarialacakChanging(value);
					this.SendPropertyChanging();
					this._uvadeli_ticarialacak = value;
					this.SendPropertyChanged("uvadeli_ticarialacak");
					this.Onuvadeli_ticarialacakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fkiralama_alacak", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> fkiralama_alacak
		{
			get
			{
				return this._fkiralama_alacak;
			}
			set
			{
				if ((this._fkiralama_alacak != value))
				{
					this.Onfkiralama_alacakChanging(value);
					this.SendPropertyChanging();
					this._fkiralama_alacak = value;
					this.SendPropertyChanged("fkiralama_alacak");
					this.Onfkiralama_alacakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_türev_enstrümanlar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> türev_enstrümanlar
		{
			get
			{
				return this._türev_enstrümanlar;
			}
			set
			{
				if ((this._türev_enstrümanlar != value))
				{
					this.Ontürev_enstrümanlarChanging(value);
					this.SendPropertyChanging();
					this._türev_enstrümanlar = value;
					this.SendPropertyChanged("türev_enstrümanlar");
					this.Ontürev_enstrümanlarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finansal_yatirim", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> finansal_yatirim
		{
			get
			{
				return this._finansal_yatirim;
			}
			set
			{
				if ((this._finansal_yatirim != value))
				{
					this.Onfinansal_yatirimChanging(value);
					this.SendPropertyChanging();
					this._finansal_yatirim = value;
					this.SendPropertyChanged("finansal_yatirim");
					this.Onfinansal_yatirimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canli_varliklar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> canli_varliklar
		{
			get
			{
				return this._canli_varliklar;
			}
			set
			{
				if ((this._canli_varliklar != value))
				{
					this.Oncanli_varliklarChanging(value);
					this.SendPropertyChanging();
					this._canli_varliklar = value;
					this.SendPropertyChanged("canli_varliklar");
					this.Oncanli_varliklarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stoklar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> stoklar
		{
			get
			{
				return this._stoklar;
			}
			set
			{
				if ((this._stoklar != value))
				{
					this.OnstoklarChanging(value);
					this.SendPropertyChanging();
					this._stoklar = value;
					this.SendPropertyChanged("stoklar");
					this.OnstoklarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mduran_varliklar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> mduran_varliklar
		{
			get
			{
				return this._mduran_varliklar;
			}
			set
			{
				if ((this._mduran_varliklar != value))
				{
					this.Onmduran_varliklarChanging(value);
					this.SendPropertyChanging();
					this._mduran_varliklar = value;
					this.SendPropertyChanged("mduran_varliklar");
					this.Onmduran_varliklarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_molmayan_duranvarlik", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> molmayan_duranvarlik
		{
			get
			{
				return this._molmayan_duranvarlik;
			}
			set
			{
				if ((this._molmayan_duranvarlik != value))
				{
					this.Onmolmayan_duranvarlikChanging(value);
					this.SendPropertyChanging();
					this._molmayan_duranvarlik = value;
					this.SendPropertyChanged("molmayan_duranvarlik");
					this.Onmolmayan_duranvarlikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finansal_duranvarlik", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> finansal_duranvarlik
		{
			get
			{
				return this._finansal_duranvarlik;
			}
			set
			{
				if ((this._finansal_duranvarlik != value))
				{
					this.Onfinansal_duranvarlikChanging(value);
					this.SendPropertyChanging();
					this._finansal_duranvarlik = value;
					this.SendPropertyChanged("finansal_duranvarlik");
					this.Onfinansal_duranvarlikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesinodenmis_giderler", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> pesinodenmis_giderler
		{
			get
			{
				return this._pesinodenmis_giderler;
			}
			set
			{
				if ((this._pesinodenmis_giderler != value))
				{
					this.Onpesinodenmis_giderlerChanging(value);
					this.SendPropertyChanging();
					this._pesinodenmis_giderler = value;
					this.SendPropertyChanged("pesinodenmis_giderler");
					this.Onpesinodenmis_giderlerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pozitif_negatif", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> pozitif_negatif
		{
			get
			{
				return this._pozitif_negatif;
			}
			set
			{
				if ((this._pozitif_negatif != value))
				{
					this.Onpozitif_negatifChanging(value);
					this.SendPropertyChanging();
					this._pozitif_negatif = value;
					this.SendPropertyChanged("pozitif_negatif");
					this.Onpozitif_negatifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sirket_adi", DbType="NVarChar(500)")]
		public string sirket_adi
		{
			get
			{
				return this._sirket_adi;
			}
			set
			{
				if ((this._sirket_adi != value))
				{
					this.Onsirket_adiChanging(value);
					this.SendPropertyChanging();
					this._sirket_adi = value;
					this.SendPropertyChanged("sirket_adi");
					this.Onsirket_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duranvarlik_toplami", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> duranvarlik_toplami
		{
			get
			{
				return this._duranvarlik_toplami;
			}
			set
			{
				if ((this._duranvarlik_toplami != value))
				{
					this.Onduranvarlik_toplamiChanging(value);
					this.SendPropertyChanging();
					this._duranvarlik_toplami = value;
					this.SendPropertyChanged("duranvarlik_toplami");
					this.Onduranvarlik_toplamiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kayit_adi", DbType="NVarChar(500)")]
		public string kayit_adi
		{
			get
			{
				return this._kayit_adi;
			}
			set
			{
				if ((this._kayit_adi != value))
				{
					this.Onkayit_adiChanging(value);
					this.SendPropertyChanging();
					this._kayit_adi = value;
					this.SendPropertyChanged("kayit_adi");
					this.Onkayit_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dduran_varliklar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> dduran_varliklar
		{
			get
			{
				return this._dduran_varliklar;
			}
			set
			{
				if ((this._dduran_varliklar != value))
				{
					this.Ondduran_varliklarChanging(value);
					this.SendPropertyChanging();
					this._dduran_varliklar = value;
					this.SendPropertyChanged("dduran_varliklar");
					this.Ondduran_varliklarChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonenVarlik")]
	public partial class DonenVarlik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _donen_id;
		
		private System.Nullable<decimal> _hazir_degerler;
		
		private System.Nullable<decimal> _finansal_yatirimlar;
		
		private System.Nullable<decimal> _menkul_kiymetler;
		
		private System.Nullable<decimal> _krediler_avanslar;
		
		private System.Nullable<decimal> _kisavadeli_alacaklar;
		
		private System.Nullable<decimal> _finansalkiralama_alacaklar;
		
		private System.Nullable<decimal> _dkisavadeli_alacaklar;
		
		private System.Nullable<decimal> _stoklar;
		
		private System.Nullable<decimal> _ddönen_varliklar;
		
		private System.Nullable<decimal> _türev_enstrümanlar;
		
		private System.Nullable<decimal> _pesinodenmis_giderler;
		
		private System.Nullable<decimal> _canli_varliklar;
		
		private System.Nullable<decimal> _donenvarlik_toplami;
		
		private string _sirket_adi;
		
		private System.Nullable<System.DateTime> _kayit_tarihi;
		
		private string _kayit_adi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondonen_idChanging(int value);
    partial void Ondonen_idChanged();
    partial void Onhazir_degerlerChanging(System.Nullable<decimal> value);
    partial void Onhazir_degerlerChanged();
    partial void Onfinansal_yatirimlarChanging(System.Nullable<decimal> value);
    partial void Onfinansal_yatirimlarChanged();
    partial void Onmenkul_kiymetlerChanging(System.Nullable<decimal> value);
    partial void Onmenkul_kiymetlerChanged();
    partial void Onkrediler_avanslarChanging(System.Nullable<decimal> value);
    partial void Onkrediler_avanslarChanged();
    partial void Onkisavadeli_alacaklarChanging(System.Nullable<decimal> value);
    partial void Onkisavadeli_alacaklarChanged();
    partial void Onfinansalkiralama_alacaklarChanging(System.Nullable<decimal> value);
    partial void Onfinansalkiralama_alacaklarChanged();
    partial void Ondkisavadeli_alacaklarChanging(System.Nullable<decimal> value);
    partial void Ondkisavadeli_alacaklarChanged();
    partial void OnstoklarChanging(System.Nullable<decimal> value);
    partial void OnstoklarChanged();
    partial void Onddönen_varliklarChanging(System.Nullable<decimal> value);
    partial void Onddönen_varliklarChanged();
    partial void Ontürev_enstrümanlarChanging(System.Nullable<decimal> value);
    partial void Ontürev_enstrümanlarChanged();
    partial void Onpesinodenmis_giderlerChanging(System.Nullable<decimal> value);
    partial void Onpesinodenmis_giderlerChanged();
    partial void Oncanli_varliklarChanging(System.Nullable<decimal> value);
    partial void Oncanli_varliklarChanged();
    partial void Ondonenvarlik_toplamiChanging(System.Nullable<decimal> value);
    partial void Ondonenvarlik_toplamiChanged();
    partial void Onsirket_adiChanging(string value);
    partial void Onsirket_adiChanged();
    partial void Onkayit_tarihiChanging(System.Nullable<System.DateTime> value);
    partial void Onkayit_tarihiChanged();
    partial void Onkayit_adiChanging(string value);
    partial void Onkayit_adiChanged();
    #endregion
		
		public DonenVarlik()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donen_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int donen_id
		{
			get
			{
				return this._donen_id;
			}
			set
			{
				if ((this._donen_id != value))
				{
					this.Ondonen_idChanging(value);
					this.SendPropertyChanging();
					this._donen_id = value;
					this.SendPropertyChanged("donen_id");
					this.Ondonen_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hazir_degerler", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> hazir_degerler
		{
			get
			{
				return this._hazir_degerler;
			}
			set
			{
				if ((this._hazir_degerler != value))
				{
					this.Onhazir_degerlerChanging(value);
					this.SendPropertyChanging();
					this._hazir_degerler = value;
					this.SendPropertyChanged("hazir_degerler");
					this.Onhazir_degerlerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finansal_yatirimlar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> finansal_yatirimlar
		{
			get
			{
				return this._finansal_yatirimlar;
			}
			set
			{
				if ((this._finansal_yatirimlar != value))
				{
					this.Onfinansal_yatirimlarChanging(value);
					this.SendPropertyChanging();
					this._finansal_yatirimlar = value;
					this.SendPropertyChanged("finansal_yatirimlar");
					this.Onfinansal_yatirimlarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menkul_kiymetler", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> menkul_kiymetler
		{
			get
			{
				return this._menkul_kiymetler;
			}
			set
			{
				if ((this._menkul_kiymetler != value))
				{
					this.Onmenkul_kiymetlerChanging(value);
					this.SendPropertyChanging();
					this._menkul_kiymetler = value;
					this.SendPropertyChanged("menkul_kiymetler");
					this.Onmenkul_kiymetlerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_krediler_avanslar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> krediler_avanslar
		{
			get
			{
				return this._krediler_avanslar;
			}
			set
			{
				if ((this._krediler_avanslar != value))
				{
					this.Onkrediler_avanslarChanging(value);
					this.SendPropertyChanging();
					this._krediler_avanslar = value;
					this.SendPropertyChanged("krediler_avanslar");
					this.Onkrediler_avanslarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kisavadeli_alacaklar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> kisavadeli_alacaklar
		{
			get
			{
				return this._kisavadeli_alacaklar;
			}
			set
			{
				if ((this._kisavadeli_alacaklar != value))
				{
					this.Onkisavadeli_alacaklarChanging(value);
					this.SendPropertyChanging();
					this._kisavadeli_alacaklar = value;
					this.SendPropertyChanged("kisavadeli_alacaklar");
					this.Onkisavadeli_alacaklarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finansalkiralama_alacaklar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> finansalkiralama_alacaklar
		{
			get
			{
				return this._finansalkiralama_alacaklar;
			}
			set
			{
				if ((this._finansalkiralama_alacaklar != value))
				{
					this.Onfinansalkiralama_alacaklarChanging(value);
					this.SendPropertyChanging();
					this._finansalkiralama_alacaklar = value;
					this.SendPropertyChanged("finansalkiralama_alacaklar");
					this.Onfinansalkiralama_alacaklarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dkisavadeli_alacaklar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> dkisavadeli_alacaklar
		{
			get
			{
				return this._dkisavadeli_alacaklar;
			}
			set
			{
				if ((this._dkisavadeli_alacaklar != value))
				{
					this.Ondkisavadeli_alacaklarChanging(value);
					this.SendPropertyChanging();
					this._dkisavadeli_alacaklar = value;
					this.SendPropertyChanged("dkisavadeli_alacaklar");
					this.Ondkisavadeli_alacaklarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stoklar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> stoklar
		{
			get
			{
				return this._stoklar;
			}
			set
			{
				if ((this._stoklar != value))
				{
					this.OnstoklarChanging(value);
					this.SendPropertyChanging();
					this._stoklar = value;
					this.SendPropertyChanged("stoklar");
					this.OnstoklarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ddönen_varliklar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> ddönen_varliklar
		{
			get
			{
				return this._ddönen_varliklar;
			}
			set
			{
				if ((this._ddönen_varliklar != value))
				{
					this.Onddönen_varliklarChanging(value);
					this.SendPropertyChanging();
					this._ddönen_varliklar = value;
					this.SendPropertyChanged("ddönen_varliklar");
					this.Onddönen_varliklarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_türev_enstrümanlar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> türev_enstrümanlar
		{
			get
			{
				return this._türev_enstrümanlar;
			}
			set
			{
				if ((this._türev_enstrümanlar != value))
				{
					this.Ontürev_enstrümanlarChanging(value);
					this.SendPropertyChanging();
					this._türev_enstrümanlar = value;
					this.SendPropertyChanged("türev_enstrümanlar");
					this.Ontürev_enstrümanlarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesinodenmis_giderler", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> pesinodenmis_giderler
		{
			get
			{
				return this._pesinodenmis_giderler;
			}
			set
			{
				if ((this._pesinodenmis_giderler != value))
				{
					this.Onpesinodenmis_giderlerChanging(value);
					this.SendPropertyChanging();
					this._pesinodenmis_giderler = value;
					this.SendPropertyChanged("pesinodenmis_giderler");
					this.Onpesinodenmis_giderlerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canli_varliklar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> canli_varliklar
		{
			get
			{
				return this._canli_varliklar;
			}
			set
			{
				if ((this._canli_varliklar != value))
				{
					this.Oncanli_varliklarChanging(value);
					this.SendPropertyChanging();
					this._canli_varliklar = value;
					this.SendPropertyChanged("canli_varliklar");
					this.Oncanli_varliklarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donenvarlik_toplami", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> donenvarlik_toplami
		{
			get
			{
				return this._donenvarlik_toplami;
			}
			set
			{
				if ((this._donenvarlik_toplami != value))
				{
					this.Ondonenvarlik_toplamiChanging(value);
					this.SendPropertyChanging();
					this._donenvarlik_toplami = value;
					this.SendPropertyChanged("donenvarlik_toplami");
					this.Ondonenvarlik_toplamiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sirket_adi", DbType="NVarChar(500)")]
		public string sirket_adi
		{
			get
			{
				return this._sirket_adi;
			}
			set
			{
				if ((this._sirket_adi != value))
				{
					this.Onsirket_adiChanging(value);
					this.SendPropertyChanging();
					this._sirket_adi = value;
					this.SendPropertyChanged("sirket_adi");
					this.Onsirket_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kayit_tarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> kayit_tarihi
		{
			get
			{
				return this._kayit_tarihi;
			}
			set
			{
				if ((this._kayit_tarihi != value))
				{
					this.Onkayit_tarihiChanging(value);
					this.SendPropertyChanging();
					this._kayit_tarihi = value;
					this.SendPropertyChanged("kayit_tarihi");
					this.Onkayit_tarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kayit_adi", DbType="NVarChar(500)")]
		public string kayit_adi
		{
			get
			{
				return this._kayit_adi;
			}
			set
			{
				if ((this._kayit_adi != value))
				{
					this.Onkayit_adiChanging(value);
					this.SendPropertyChanging();
					this._kayit_adi = value;
					this.SendPropertyChanged("kayit_adi");
					this.Onkayit_adiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AktifPasif")]
	public partial class AktifPasif : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<decimal> _aktif_toplam;
		
		private System.Nullable<decimal> _pasif_toplam;
		
		private string _sirket_adi;
		
		private string _kayit_adi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onaktif_toplamChanging(System.Nullable<decimal> value);
    partial void Onaktif_toplamChanged();
    partial void Onpasif_toplamChanging(System.Nullable<decimal> value);
    partial void Onpasif_toplamChanged();
    partial void Onsirket_adiChanging(string value);
    partial void Onsirket_adiChanged();
    partial void Onkayit_adiChanging(string value);
    partial void Onkayit_adiChanged();
    #endregion
		
		public AktifPasif()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aktif_toplam", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> aktif_toplam
		{
			get
			{
				return this._aktif_toplam;
			}
			set
			{
				if ((this._aktif_toplam != value))
				{
					this.Onaktif_toplamChanging(value);
					this.SendPropertyChanging();
					this._aktif_toplam = value;
					this.SendPropertyChanged("aktif_toplam");
					this.Onaktif_toplamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pasif_toplam", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> pasif_toplam
		{
			get
			{
				return this._pasif_toplam;
			}
			set
			{
				if ((this._pasif_toplam != value))
				{
					this.Onpasif_toplamChanging(value);
					this.SendPropertyChanging();
					this._pasif_toplam = value;
					this.SendPropertyChanged("pasif_toplam");
					this.Onpasif_toplamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sirket_adi", DbType="NVarChar(500)")]
		public string sirket_adi
		{
			get
			{
				return this._sirket_adi;
			}
			set
			{
				if ((this._sirket_adi != value))
				{
					this.Onsirket_adiChanging(value);
					this.SendPropertyChanging();
					this._sirket_adi = value;
					this.SendPropertyChanged("sirket_adi");
					this.Onsirket_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kayit_adi", DbType="NVarChar(500)")]
		public string kayit_adi
		{
			get
			{
				return this._kayit_adi;
			}
			set
			{
				if ((this._kayit_adi != value))
				{
					this.Onkayit_adiChanging(value);
					this.SendPropertyChanging();
					this._kayit_adi = value;
					this.SendPropertyChanged("kayit_adi");
					this.Onkayit_adiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kullanici")]
	public partial class Kullanici : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_name;
		
		private string _password;
		
		private string _name;
		
		private string _last_name;
		
		private string _security_question;
		
		private string _company;
		
		private string _company_type;
		
		private string _business_type;
		
		private string _email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void Onsecurity_questionChanging(string value);
    partial void Onsecurity_questionChanged();
    partial void OncompanyChanging(string value);
    partial void OncompanyChanged();
    partial void Oncompany_typeChanging(string value);
    partial void Oncompany_typeChanged();
    partial void Onbusiness_typeChanging(string value);
    partial void Onbusiness_typeChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public Kullanici()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(500)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(500)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(500)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="NVarChar(500)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_security_question", DbType="NVarChar(500)")]
		public string security_question
		{
			get
			{
				return this._security_question;
			}
			set
			{
				if ((this._security_question != value))
				{
					this.Onsecurity_questionChanging(value);
					this.SendPropertyChanging();
					this._security_question = value;
					this.SendPropertyChanged("security_question");
					this.Onsecurity_questionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company", DbType="NVarChar(500)")]
		public string company
		{
			get
			{
				return this._company;
			}
			set
			{
				if ((this._company != value))
				{
					this.OncompanyChanging(value);
					this.SendPropertyChanging();
					this._company = value;
					this.SendPropertyChanged("company");
					this.OncompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company_type", DbType="NVarChar(500)")]
		public string company_type
		{
			get
			{
				return this._company_type;
			}
			set
			{
				if ((this._company_type != value))
				{
					this.Oncompany_typeChanging(value);
					this.SendPropertyChanging();
					this._company_type = value;
					this.SendPropertyChanged("company_type");
					this.Oncompany_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_business_type", DbType="NVarChar(500)")]
		public string business_type
		{
			get
			{
				return this._business_type;
			}
			set
			{
				if ((this._business_type != value))
				{
					this.Onbusiness_typeChanging(value);
					this.SendPropertyChanging();
					this._business_type = value;
					this.SendPropertyChanged("business_type");
					this.Onbusiness_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(500)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ozkaynak")]
	public partial class Ozkaynak : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ozkaynak_id;
		
		private System.Nullable<decimal> _sermaye;
		
		private System.Nullable<decimal> _odenmeyen_sermaye;
		
		private System.Nullable<decimal> _sermaye_avansi;
		
		private System.Nullable<decimal> _sermaye_yedekleri;
		
		private System.Nullable<decimal> _katki_sermaye;
		
		private System.Nullable<decimal> _emisyon_primi;
		
		private System.Nullable<decimal> _yeniden_degerleme;
		
		private System.Nullable<decimal> _kar_yedekleri;
		
		private System.Nullable<decimal> _dagilmamis_sermaye;
		
		private System.Nullable<decimal> _netdonem_kari;
		
		private System.Nullable<decimal> _zarartelafi_fonu;
		
		private System.Nullable<decimal> _gecmisyil_kar;
		
		private System.Nullable<decimal> _gecmisyil_zarar;
		
		private System.Nullable<decimal> _yatirim_tesfikleri;
		
		private string _sirket_adi;
		
		private System.Nullable<decimal> _ozkaynak_toplami;
		
		private System.Nullable<decimal> _netdonem_zarari;
		
		private string _kayit_adi;
		
		private System.Nullable<decimal> _iodenmis_sermaye;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onozkaynak_idChanging(int value);
    partial void Onozkaynak_idChanged();
    partial void OnsermayeChanging(System.Nullable<decimal> value);
    partial void OnsermayeChanged();
    partial void Onodenmeyen_sermayeChanging(System.Nullable<decimal> value);
    partial void Onodenmeyen_sermayeChanged();
    partial void Onsermaye_avansiChanging(System.Nullable<decimal> value);
    partial void Onsermaye_avansiChanged();
    partial void Onsermaye_yedekleriChanging(System.Nullable<decimal> value);
    partial void Onsermaye_yedekleriChanged();
    partial void Onkatki_sermayeChanging(System.Nullable<decimal> value);
    partial void Onkatki_sermayeChanged();
    partial void Onemisyon_primiChanging(System.Nullable<decimal> value);
    partial void Onemisyon_primiChanged();
    partial void Onyeniden_degerlemeChanging(System.Nullable<decimal> value);
    partial void Onyeniden_degerlemeChanged();
    partial void Onkar_yedekleriChanging(System.Nullable<decimal> value);
    partial void Onkar_yedekleriChanged();
    partial void Ondagilmamis_sermayeChanging(System.Nullable<decimal> value);
    partial void Ondagilmamis_sermayeChanged();
    partial void Onnetdonem_kariChanging(System.Nullable<decimal> value);
    partial void Onnetdonem_kariChanged();
    partial void Onzarartelafi_fonuChanging(System.Nullable<decimal> value);
    partial void Onzarartelafi_fonuChanged();
    partial void Ongecmisyil_karChanging(System.Nullable<decimal> value);
    partial void Ongecmisyil_karChanged();
    partial void Ongecmisyil_zararChanging(System.Nullable<decimal> value);
    partial void Ongecmisyil_zararChanged();
    partial void Onyatirim_tesfikleriChanging(System.Nullable<decimal> value);
    partial void Onyatirim_tesfikleriChanged();
    partial void Onsirket_adiChanging(string value);
    partial void Onsirket_adiChanged();
    partial void Onozkaynak_toplamiChanging(System.Nullable<decimal> value);
    partial void Onozkaynak_toplamiChanged();
    partial void Onnetdonem_zarariChanging(System.Nullable<decimal> value);
    partial void Onnetdonem_zarariChanged();
    partial void Onkayit_adiChanging(string value);
    partial void Onkayit_adiChanged();
    partial void Oniodenmis_sermayeChanging(System.Nullable<decimal> value);
    partial void Oniodenmis_sermayeChanged();
    #endregion
		
		public Ozkaynak()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ozkaynak_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ozkaynak_id
		{
			get
			{
				return this._ozkaynak_id;
			}
			set
			{
				if ((this._ozkaynak_id != value))
				{
					this.Onozkaynak_idChanging(value);
					this.SendPropertyChanging();
					this._ozkaynak_id = value;
					this.SendPropertyChanged("ozkaynak_id");
					this.Onozkaynak_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sermaye", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> sermaye
		{
			get
			{
				return this._sermaye;
			}
			set
			{
				if ((this._sermaye != value))
				{
					this.OnsermayeChanging(value);
					this.SendPropertyChanging();
					this._sermaye = value;
					this.SendPropertyChanged("sermaye");
					this.OnsermayeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odenmeyen_sermaye", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> odenmeyen_sermaye
		{
			get
			{
				return this._odenmeyen_sermaye;
			}
			set
			{
				if ((this._odenmeyen_sermaye != value))
				{
					this.Onodenmeyen_sermayeChanging(value);
					this.SendPropertyChanging();
					this._odenmeyen_sermaye = value;
					this.SendPropertyChanged("odenmeyen_sermaye");
					this.Onodenmeyen_sermayeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sermaye_avansi", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> sermaye_avansi
		{
			get
			{
				return this._sermaye_avansi;
			}
			set
			{
				if ((this._sermaye_avansi != value))
				{
					this.Onsermaye_avansiChanging(value);
					this.SendPropertyChanging();
					this._sermaye_avansi = value;
					this.SendPropertyChanged("sermaye_avansi");
					this.Onsermaye_avansiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sermaye_yedekleri", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> sermaye_yedekleri
		{
			get
			{
				return this._sermaye_yedekleri;
			}
			set
			{
				if ((this._sermaye_yedekleri != value))
				{
					this.Onsermaye_yedekleriChanging(value);
					this.SendPropertyChanging();
					this._sermaye_yedekleri = value;
					this.SendPropertyChanged("sermaye_yedekleri");
					this.Onsermaye_yedekleriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_katki_sermaye", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> katki_sermaye
		{
			get
			{
				return this._katki_sermaye;
			}
			set
			{
				if ((this._katki_sermaye != value))
				{
					this.Onkatki_sermayeChanging(value);
					this.SendPropertyChanging();
					this._katki_sermaye = value;
					this.SendPropertyChanged("katki_sermaye");
					this.Onkatki_sermayeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emisyon_primi", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> emisyon_primi
		{
			get
			{
				return this._emisyon_primi;
			}
			set
			{
				if ((this._emisyon_primi != value))
				{
					this.Onemisyon_primiChanging(value);
					this.SendPropertyChanging();
					this._emisyon_primi = value;
					this.SendPropertyChanged("emisyon_primi");
					this.Onemisyon_primiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yeniden_degerleme", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> yeniden_degerleme
		{
			get
			{
				return this._yeniden_degerleme;
			}
			set
			{
				if ((this._yeniden_degerleme != value))
				{
					this.Onyeniden_degerlemeChanging(value);
					this.SendPropertyChanging();
					this._yeniden_degerleme = value;
					this.SendPropertyChanged("yeniden_degerleme");
					this.Onyeniden_degerlemeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kar_yedekleri", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> kar_yedekleri
		{
			get
			{
				return this._kar_yedekleri;
			}
			set
			{
				if ((this._kar_yedekleri != value))
				{
					this.Onkar_yedekleriChanging(value);
					this.SendPropertyChanging();
					this._kar_yedekleri = value;
					this.SendPropertyChanged("kar_yedekleri");
					this.Onkar_yedekleriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dagilmamis_sermaye", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> dagilmamis_sermaye
		{
			get
			{
				return this._dagilmamis_sermaye;
			}
			set
			{
				if ((this._dagilmamis_sermaye != value))
				{
					this.Ondagilmamis_sermayeChanging(value);
					this.SendPropertyChanging();
					this._dagilmamis_sermaye = value;
					this.SendPropertyChanged("dagilmamis_sermaye");
					this.Ondagilmamis_sermayeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_netdonem_kari", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> netdonem_kari
		{
			get
			{
				return this._netdonem_kari;
			}
			set
			{
				if ((this._netdonem_kari != value))
				{
					this.Onnetdonem_kariChanging(value);
					this.SendPropertyChanging();
					this._netdonem_kari = value;
					this.SendPropertyChanged("netdonem_kari");
					this.Onnetdonem_kariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zarartelafi_fonu", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> zarartelafi_fonu
		{
			get
			{
				return this._zarartelafi_fonu;
			}
			set
			{
				if ((this._zarartelafi_fonu != value))
				{
					this.Onzarartelafi_fonuChanging(value);
					this.SendPropertyChanging();
					this._zarartelafi_fonu = value;
					this.SendPropertyChanged("zarartelafi_fonu");
					this.Onzarartelafi_fonuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gecmisyil_kar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> gecmisyil_kar
		{
			get
			{
				return this._gecmisyil_kar;
			}
			set
			{
				if ((this._gecmisyil_kar != value))
				{
					this.Ongecmisyil_karChanging(value);
					this.SendPropertyChanging();
					this._gecmisyil_kar = value;
					this.SendPropertyChanged("gecmisyil_kar");
					this.Ongecmisyil_karChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gecmisyil_zarar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> gecmisyil_zarar
		{
			get
			{
				return this._gecmisyil_zarar;
			}
			set
			{
				if ((this._gecmisyil_zarar != value))
				{
					this.Ongecmisyil_zararChanging(value);
					this.SendPropertyChanging();
					this._gecmisyil_zarar = value;
					this.SendPropertyChanged("gecmisyil_zarar");
					this.Ongecmisyil_zararChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yatirim_tesfikleri", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> yatirim_tesfikleri
		{
			get
			{
				return this._yatirim_tesfikleri;
			}
			set
			{
				if ((this._yatirim_tesfikleri != value))
				{
					this.Onyatirim_tesfikleriChanging(value);
					this.SendPropertyChanging();
					this._yatirim_tesfikleri = value;
					this.SendPropertyChanged("yatirim_tesfikleri");
					this.Onyatirim_tesfikleriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sirket_adi", DbType="NVarChar(500)")]
		public string sirket_adi
		{
			get
			{
				return this._sirket_adi;
			}
			set
			{
				if ((this._sirket_adi != value))
				{
					this.Onsirket_adiChanging(value);
					this.SendPropertyChanging();
					this._sirket_adi = value;
					this.SendPropertyChanged("sirket_adi");
					this.Onsirket_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ozkaynak_toplami", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ozkaynak_toplami
		{
			get
			{
				return this._ozkaynak_toplami;
			}
			set
			{
				if ((this._ozkaynak_toplami != value))
				{
					this.Onozkaynak_toplamiChanging(value);
					this.SendPropertyChanging();
					this._ozkaynak_toplami = value;
					this.SendPropertyChanged("ozkaynak_toplami");
					this.Onozkaynak_toplamiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_netdonem_zarari", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> netdonem_zarari
		{
			get
			{
				return this._netdonem_zarari;
			}
			set
			{
				if ((this._netdonem_zarari != value))
				{
					this.Onnetdonem_zarariChanging(value);
					this.SendPropertyChanging();
					this._netdonem_zarari = value;
					this.SendPropertyChanged("netdonem_zarari");
					this.Onnetdonem_zarariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kayit_adi", DbType="NVarChar(500)")]
		public string kayit_adi
		{
			get
			{
				return this._kayit_adi;
			}
			set
			{
				if ((this._kayit_adi != value))
				{
					this.Onkayit_adiChanging(value);
					this.SendPropertyChanging();
					this._kayit_adi = value;
					this.SendPropertyChanged("kayit_adi");
					this.Onkayit_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iodenmis_sermaye", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> iodenmis_sermaye
		{
			get
			{
				return this._iodenmis_sermaye;
			}
			set
			{
				if ((this._iodenmis_sermaye != value))
				{
					this.Oniodenmis_sermayeChanging(value);
					this.SendPropertyChanging();
					this._iodenmis_sermaye = value;
					this.SendPropertyChanged("iodenmis_sermaye");
					this.Oniodenmis_sermayeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KVYK")]
	public partial class KVYK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kvyk_id;
		
		private System.Nullable<decimal> _finansal_borclar;
		
		private System.Nullable<decimal> _mevduat;
		
		private System.Nullable<decimal> _turev_araclar;
		
		private System.Nullable<decimal> _bloke_hesaplar;
		
		private System.Nullable<decimal> _factoring_borclar;
		
		private System.Nullable<decimal> _sigorta_karsiligi;
		
		private System.Nullable<decimal> _dfinansal_yukumluluk;
		
		private System.Nullable<decimal> _borcgider_karsiligi;
		
		private System.Nullable<decimal> _ticari_borclar;
		
		private System.Nullable<decimal> _iliskili_borclar;
		
		private System.Nullable<decimal> _alinan_krediler;
		
		private System.Nullable<decimal> _diger_borclar;
		
		private System.Nullable<decimal> _alinan_avanslar;
		
		private System.Nullable<decimal> _ertelenmis_gelirler;
		
		private string _sirket_adi;
		
		private System.Nullable<decimal> _kvyk_toplami;
		
		private string _kayit_adi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkvyk_idChanging(int value);
    partial void Onkvyk_idChanged();
    partial void Onfinansal_borclarChanging(System.Nullable<decimal> value);
    partial void Onfinansal_borclarChanged();
    partial void OnmevduatChanging(System.Nullable<decimal> value);
    partial void OnmevduatChanged();
    partial void Onturev_araclarChanging(System.Nullable<decimal> value);
    partial void Onturev_araclarChanged();
    partial void Onbloke_hesaplarChanging(System.Nullable<decimal> value);
    partial void Onbloke_hesaplarChanged();
    partial void Onfactoring_borclarChanging(System.Nullable<decimal> value);
    partial void Onfactoring_borclarChanged();
    partial void Onsigorta_karsiligiChanging(System.Nullable<decimal> value);
    partial void Onsigorta_karsiligiChanged();
    partial void Ondfinansal_yukumlulukChanging(System.Nullable<decimal> value);
    partial void Ondfinansal_yukumlulukChanged();
    partial void Onborcgider_karsiligiChanging(System.Nullable<decimal> value);
    partial void Onborcgider_karsiligiChanged();
    partial void Onticari_borclarChanging(System.Nullable<decimal> value);
    partial void Onticari_borclarChanged();
    partial void Oniliskili_borclarChanging(System.Nullable<decimal> value);
    partial void Oniliskili_borclarChanged();
    partial void Onalinan_kredilerChanging(System.Nullable<decimal> value);
    partial void Onalinan_kredilerChanged();
    partial void Ondiger_borclarChanging(System.Nullable<decimal> value);
    partial void Ondiger_borclarChanged();
    partial void Onalinan_avanslarChanging(System.Nullable<decimal> value);
    partial void Onalinan_avanslarChanged();
    partial void Onertelenmis_gelirlerChanging(System.Nullable<decimal> value);
    partial void Onertelenmis_gelirlerChanged();
    partial void Onsirket_adiChanging(string value);
    partial void Onsirket_adiChanged();
    partial void Onkvyk_toplamiChanging(System.Nullable<decimal> value);
    partial void Onkvyk_toplamiChanged();
    partial void Onkayit_adiChanging(string value);
    partial void Onkayit_adiChanged();
    #endregion
		
		public KVYK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kvyk_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kvyk_id
		{
			get
			{
				return this._kvyk_id;
			}
			set
			{
				if ((this._kvyk_id != value))
				{
					this.Onkvyk_idChanging(value);
					this.SendPropertyChanging();
					this._kvyk_id = value;
					this.SendPropertyChanged("kvyk_id");
					this.Onkvyk_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finansal_borclar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> finansal_borclar
		{
			get
			{
				return this._finansal_borclar;
			}
			set
			{
				if ((this._finansal_borclar != value))
				{
					this.Onfinansal_borclarChanging(value);
					this.SendPropertyChanging();
					this._finansal_borclar = value;
					this.SendPropertyChanged("finansal_borclar");
					this.Onfinansal_borclarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mevduat", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> mevduat
		{
			get
			{
				return this._mevduat;
			}
			set
			{
				if ((this._mevduat != value))
				{
					this.OnmevduatChanging(value);
					this.SendPropertyChanging();
					this._mevduat = value;
					this.SendPropertyChanged("mevduat");
					this.OnmevduatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turev_araclar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> turev_araclar
		{
			get
			{
				return this._turev_araclar;
			}
			set
			{
				if ((this._turev_araclar != value))
				{
					this.Onturev_araclarChanging(value);
					this.SendPropertyChanging();
					this._turev_araclar = value;
					this.SendPropertyChanged("turev_araclar");
					this.Onturev_araclarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bloke_hesaplar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> bloke_hesaplar
		{
			get
			{
				return this._bloke_hesaplar;
			}
			set
			{
				if ((this._bloke_hesaplar != value))
				{
					this.Onbloke_hesaplarChanging(value);
					this.SendPropertyChanging();
					this._bloke_hesaplar = value;
					this.SendPropertyChanged("bloke_hesaplar");
					this.Onbloke_hesaplarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factoring_borclar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> factoring_borclar
		{
			get
			{
				return this._factoring_borclar;
			}
			set
			{
				if ((this._factoring_borclar != value))
				{
					this.Onfactoring_borclarChanging(value);
					this.SendPropertyChanging();
					this._factoring_borclar = value;
					this.SendPropertyChanged("factoring_borclar");
					this.Onfactoring_borclarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sigorta_karsiligi", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> sigorta_karsiligi
		{
			get
			{
				return this._sigorta_karsiligi;
			}
			set
			{
				if ((this._sigorta_karsiligi != value))
				{
					this.Onsigorta_karsiligiChanging(value);
					this.SendPropertyChanging();
					this._sigorta_karsiligi = value;
					this.SendPropertyChanged("sigorta_karsiligi");
					this.Onsigorta_karsiligiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dfinansal_yukumluluk", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> dfinansal_yukumluluk
		{
			get
			{
				return this._dfinansal_yukumluluk;
			}
			set
			{
				if ((this._dfinansal_yukumluluk != value))
				{
					this.Ondfinansal_yukumlulukChanging(value);
					this.SendPropertyChanging();
					this._dfinansal_yukumluluk = value;
					this.SendPropertyChanged("dfinansal_yukumluluk");
					this.Ondfinansal_yukumlulukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_borcgider_karsiligi", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> borcgider_karsiligi
		{
			get
			{
				return this._borcgider_karsiligi;
			}
			set
			{
				if ((this._borcgider_karsiligi != value))
				{
					this.Onborcgider_karsiligiChanging(value);
					this.SendPropertyChanging();
					this._borcgider_karsiligi = value;
					this.SendPropertyChanged("borcgider_karsiligi");
					this.Onborcgider_karsiligiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ticari_borclar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> ticari_borclar
		{
			get
			{
				return this._ticari_borclar;
			}
			set
			{
				if ((this._ticari_borclar != value))
				{
					this.Onticari_borclarChanging(value);
					this.SendPropertyChanging();
					this._ticari_borclar = value;
					this.SendPropertyChanged("ticari_borclar");
					this.Onticari_borclarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iliskili_borclar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> iliskili_borclar
		{
			get
			{
				return this._iliskili_borclar;
			}
			set
			{
				if ((this._iliskili_borclar != value))
				{
					this.Oniliskili_borclarChanging(value);
					this.SendPropertyChanging();
					this._iliskili_borclar = value;
					this.SendPropertyChanged("iliskili_borclar");
					this.Oniliskili_borclarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alinan_krediler", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> alinan_krediler
		{
			get
			{
				return this._alinan_krediler;
			}
			set
			{
				if ((this._alinan_krediler != value))
				{
					this.Onalinan_kredilerChanging(value);
					this.SendPropertyChanging();
					this._alinan_krediler = value;
					this.SendPropertyChanged("alinan_krediler");
					this.Onalinan_kredilerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diger_borclar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> diger_borclar
		{
			get
			{
				return this._diger_borclar;
			}
			set
			{
				if ((this._diger_borclar != value))
				{
					this.Ondiger_borclarChanging(value);
					this.SendPropertyChanging();
					this._diger_borclar = value;
					this.SendPropertyChanged("diger_borclar");
					this.Ondiger_borclarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alinan_avanslar", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> alinan_avanslar
		{
			get
			{
				return this._alinan_avanslar;
			}
			set
			{
				if ((this._alinan_avanslar != value))
				{
					this.Onalinan_avanslarChanging(value);
					this.SendPropertyChanging();
					this._alinan_avanslar = value;
					this.SendPropertyChanged("alinan_avanslar");
					this.Onalinan_avanslarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ertelenmis_gelirler", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> ertelenmis_gelirler
		{
			get
			{
				return this._ertelenmis_gelirler;
			}
			set
			{
				if ((this._ertelenmis_gelirler != value))
				{
					this.Onertelenmis_gelirlerChanging(value);
					this.SendPropertyChanging();
					this._ertelenmis_gelirler = value;
					this.SendPropertyChanged("ertelenmis_gelirler");
					this.Onertelenmis_gelirlerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sirket_adi", DbType="NVarChar(500)")]
		public string sirket_adi
		{
			get
			{
				return this._sirket_adi;
			}
			set
			{
				if ((this._sirket_adi != value))
				{
					this.Onsirket_adiChanging(value);
					this.SendPropertyChanging();
					this._sirket_adi = value;
					this.SendPropertyChanged("sirket_adi");
					this.Onsirket_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kvyk_toplami", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> kvyk_toplami
		{
			get
			{
				return this._kvyk_toplami;
			}
			set
			{
				if ((this._kvyk_toplami != value))
				{
					this.Onkvyk_toplamiChanging(value);
					this.SendPropertyChanging();
					this._kvyk_toplami = value;
					this.SendPropertyChanged("kvyk_toplami");
					this.Onkvyk_toplamiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kayit_adi", DbType="NVarChar(500)")]
		public string kayit_adi
		{
			get
			{
				return this._kayit_adi;
			}
			set
			{
				if ((this._kayit_adi != value))
				{
					this.Onkayit_adiChanging(value);
					this.SendPropertyChanging();
					this._kayit_adi = value;
					this.SendPropertyChanged("kayit_adi");
					this.Onkayit_adiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
